core/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("phonebook.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("i18n/", include("django.conf.urls.i18n")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

phonebook/urls.py
from django.db import router
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('contact', views.ContactViewSet)

urlpatterns = [
    path("", views.index.as_view(), name="index"),
    path("search/", views.search.as_view(), name="search"),
    path("find/", views.find.as_view(), name="find"),
    path("create/", views.CreateProfile.as_view(), name="create_profile"),
    path("register", views.Register.as_view(), name="register"),
    path("login", auth_views.LoginView.as_view(
        template_name="phonebook/login.html"), name="login"),
    path("logout", auth_views.LogoutView.as_view(
        template_name="phonebook/logout.html"), name="logout"),
    path("edit_profile/<int:pk>", views.EditProfile.as_view(), name="editprofile"),
    path("recent", views.Recent.as_view(), name="recent"),
    path("print/", views.PrintContact.as_view(), name="print"),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls))
]

phonebook/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

validator = RegexValidator(regex="^0[0-9]{2,}[0-9]{7,}$", message="invalid phone number")
# Create your models here.
class PhoneBook(models.Model):
    phone_number = models.CharField(max_length=11, verbose_name=_("phonenumber"))
    first_name = models.CharField(max_length=20, verbose_name=_("firstname"))
    last_name = models.CharField(max_length=20, verbose_name=_("lastname"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        unique_together = ["phone_number", "user"]

phonebook/forms.py
from django import forms
from .models import PhoneBook
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class NewContactForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=11, required=True)

    class Meta:
        model = PhoneBook
        fields = [
            "first_name",
            "last_name",
            "phone_number",
        ]
        exclude = ["user"]


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "username", "password1", "password2")

phonebook/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from . import forms
from .models import PhoneBook
from django.urls import reverse_lazy
from django.utils import timezone
import logging
#import weasyprint
from django.http import HttpRequest, HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import generics, viewsets
from . import serializer
from . import permisssion
from rest_framework.exceptions import NotAuthenticated
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters


logger = logging.getLogger(__name__)



@method_decorator(csrf_exempt, name="dispatch")
class CreateProfile(LoginRequiredMixin, generic.View):
    def post(self, *args, **kwargs):
        if "recent" not in self.request.session.keys():
            self.request.session["recent"] = {
                # recent : view name
            }
        self.request.session["recent"].update(
            {str(timezone.now()): "CreateProfileView"})
        self.request.session.save()
        form = forms.NewContactForm(data=self.request.POST)
        if form.is_valid():
            form.save(commit=False).user = self.request.user
            contact = form.save()
            logger.info(f"contact {contact.phone_number} created")
            return JsonResponse(
                data={
                    "success": True,
                    "pk": contact.pk,
                    "first_name": contact.first_name,
                    "last_name": contact.last_name,
                    "phone_number": contact.phone_number,
                    "user": contact.user,
                },
                status=201,
            )
        else:
            return JsonResponse(
                data={
                    "success": False,
                },
                status=400,
            )


@method_decorator(csrf_exempt, name="dispatch")
class index(LoginRequiredMixin, generic.ListView):
    """
    Show the add entry form page
    """

    extra_context = {"form": forms.NewContactForm()}
    paginate_by = 2
    template_name = "phonebook/index.html"

    def get(self, *args, **kwargs):
        if "recent" not in self.request.session.keys():
            self.request.session["recent"] = {
                # recent : view name
            }
        self.request.session["recent"][str(timezone.now())] = "indexView"
        self.request.session.save()
        print(settings.STATIC_ROOT)
        print(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
        return super().get(*args, **kwargs)

    def get_queryset(self):
        return PhoneBook.objects.filter(user=self.request.user)


class search(LoginRequiredMixin, generic.TemplateView):
    """
    Show the search form page
    """

    template_name = "phonebook/search.html"


class find(generic.View):
    """
    Finds a phonebook entry
    """

    @method_decorator(login_required)
    def get(self, *args, **kwargs):
        print("test")
        phone_number = self.request.GET.get("phone", None)
        mode = self.request.GET.get("mode", None)
        if not phone_number:
            return JsonResponse({"success": False, "error": "No number specified."}, status=400)
        if mode == "1":
            qs = PhoneBook.objects.filter(
                phone_number=phone_number, user=self.request.user)
        if mode == "2":
            qs = PhoneBook.objects.filter(
                phone_number__startswith=phone_number, user=self.request.user)
        if mode == "3":
            qs = PhoneBook.objects.filter(
                phone_number__endswith=phone_number, user=self.request.user)
        if mode == "4":
            qs = PhoneBook.objects.filter(
                phone_number__contains=phone_number, user=self.request.user)
        if "recent" not in self.request.session.keys():
            self.request.session["recent"] = {
                # recent : view name
            }
        self.request.session["recent"][str(timezone.now())] = "findView"
        self.request.session.save()
        logger.info(f"search for user")
        return JsonResponse({"results": list(qs.values()), "count": qs.count()})



class Register(generic.CreateView):
    form_class = forms.UserRegisterForm
    template_name = "phonebook/register.html"

    def get(self, *args, **kwargs):
        if "recent" not in self.request.session.keys():
            self.request.session["recent"] = {
                # recent : view name
            }
        self.request.session["recent"][str(timezone.now())] = "RegisterView"
        self.request.session.save()
        return super().get(*args, **kwargs)

    def form_valid(self, form):
        form.save()
        return redirect("login")


class EditProfile(LoginRequiredMixin, generic.UpdateView):
    model = PhoneBook
    form_class = forms.NewContactForm
    template_name = "phonebook/editprofile.html"
    success_url = reverse_lazy("index")

    def get(self, *args, **kwargs):
        if "recent" not in self.request.session.keys():
            self.request.session["recent"] = {
                # recent : view name
            }
        self.request.session["recent"][str(timezone.now())] = "editView"
        self.request.session.save()
        return super().get(*args, **kwargs)


class Recent(LoginRequiredMixin, generic.View):
    template_name = "phonebook/recent.html"

    def get(self, *args, **kwargs):
        print(list(self.request.session.get("recent", []).values())[-5:][::-1])

        return render(
            self.request,
            "phonebook/recent.html",
            context={"recent": list(self.request.session.get(
                "recent", []).values())[-5:][::-1]},
        )


class PrintContact(generic.ListView):
    def get_queryset(self):
        return PhoneBook.objects.filter(user=self.request.user)



class CustomSearchFilter(filters.SearchFilter):
    def get_search_fields(self, view, request):
        mode = request.GET.get("mode", None)
        if mode == '1':  # exact
            return ['=phone_number']
        elif mode == '2':  # starts__with
            return ['^phone_number']
        elif mode == '3':
            return ['$phone_number']
        elif mode == '4':  # contain
            return ['phone_number']
        return super(CustomSearchFilter, self).get_search_fields(view, request)


class ContactViewSet(viewsets.ModelViewSet):
    queryset = PhoneBook.objects.all()
    serializer_class = serializer.PhonebookSerializer
    permission_classes = [permisssion.IsContactOwner]
    filter_backends = [CustomSearchFilter]
    search_fields = ['phone_number']

    def get_queryset(self):
        if self.request.user.is_anonymous:
            raise NotAuthenticated('you have to login first')
        else:
            return PhoneBook.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

phonebook/templates/phonebook/base.html
<!DOCTYPE html>
{%load i18n %}
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static '/css/all.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>

<body class="d-flex flex-column h-100">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand ml-5" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'search' %}">find</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recent' %}">recent</a>
        </li>
      </ul>
      <ul class="navbar-nav my-2 mr-5 my-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href=""><span class="sr-only">{(current)}</span>{{user.username}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
        <li>
            <select name="language" class="custom-select" id = "lang" style="width:70px">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
              <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE  %} selected {% endif %}>
                {{ language.code }}
              </option>
              {% endfor %}
            </select>
        </li>
      </ul> 

    </div>
  </nav>
  <div class="container">
    {% block body %}
    {% endblock body %}
  </div>
  <script src="{% static '/js/jquery-3.6.0.js' %}"></script>
  <script src="{% static '/js/bootstrap.bundle.js' %}"></script>
  {% block scripts %}
  {% endblock scripts %}
</body>
<script>
function getCookie(name)
{
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?

            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

$.ajaxSetup({ 
     beforeSend: function(xhr, settings) {
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     } 
});
       $(document).ready(function () {
        $('#lang').change(function () {
            var lang = $('#lang').val();
            var next_url = '{{request.get_full_path}}'
            var ajax_config = {
                url: "{% url 'set_language' %}",
                data: { 
                    language: lang,
                    next: next_url,
                },
                method: 'POST',
                success: function (response) {
                  window.location.href = next_url
                }
            }
            $.ajax(ajax_config);
        });
    });

</script>
</html>

phonebook/templates/phonebook/editprofile.html
{% extends "phonebook/base.html" %}
{% block title %}edit{% endblock %}
{% block body %}
<div class="col-12">
    <h3>{{ page_title }}</h3>
    <form method="post">
        {% csrf_token %}
        {% with field=form.first_name %}
        <div class="form-group">
            <label for="{{ field.auto_id }}">{{ field.label }}</label>
            <input type="text" id="{{ field.auto_id }}" class="form-control" value="{{ field.initial }}"
                name="{{ field.name }}">
        </div>
        {% endwith %}
        {% with field=form.last_name %}
        <div class="form-group">
            <label for="{{ field.auto_id }}">{{ field.label }}</label>
            <input type="text" id="{{ field.auto_id }}" class="form-control" value="{{ field.initial }}"
                name="{{ field.name }}">
        </div>
        {% endwith %}
        {% with field=form.phone_number %}
        <div class="form-group">
            <label for="{{ field.auto_id }}">{{ field.label }}</label>
            <input type="text" id="{{ field.auto_id }}" class="form-control" value="{{ field.initial }}"
                name="{{ field.name }}">
        </div>
        {% endwith %}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

{% endblock %}

phonebook/templates/phonebook/index.html
{% extends 'phonebook/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load i18n %}
<div class="row form-group">
    {{form.first_name.name}}:
    {{form.first_name|add_class:"col form-control"}}
    {{form.last_name.name}}:
    {{form.last_name|add_class:"col form-control"}}
    {{form.phone_number.name}}:
    {{form.phone_number|add_class:"col form-control"}}
    <button id="add_phone" class='btn btn-success md-1'>add</button>
</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">{% trans "firstname" %}</th>
            <th scope="col">{% trans "lastname" %}</th>
            <th scope="col">{% trans "phonenumber" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for number in page_obj %}
        <tr>
            <td>{{number.first_name}}</td>
            <td>{{number.last_name}}</td>
            <td>{{number.phone_number}}</td>
            <td><a href="api/v1/contact/{{number.pk}}">✏</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
 <a  href="{% url 'print'%}"><i class="fas fa-print fa-2x"></i></a>
<div>
    <div class="pagination">
        <span class="current">
            {% if page_obj.has_previous %}
            <a class="page-link" href="?page=1">&laquo; first</a>
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock body %}
{% block scripts %}
<script>
    $(document).ready(function () {
        $('#add_phone').on('click', function (event) {
            var first_name = $('#id_first_name').val();
            var last_name = $('#id_last_name').val();
            var phone_number = $('#id_phone_number').val();
            $.ajax({
                url: 'api/v1/contact/',
                method: 'post',
                data: {
                    first_name: first_name,
                    last_name: last_name,
                    phone_number: phone_number,
                },
                success: function (response) {
                    alert("Saved");
                },
                error: function (response) {
                    alert("Error Enter valid number");
                }
            });
        });
    });
</script>
{% endblock %}

phonebook/templates/phonebook/login.html
{% extends "phonebook/base.html" %}
{% block title %}Login{% endblock %}
{% block body %}
{% if message %}
<div>
    {{ message }}
    <a href="{% url 'register' %}"> Create Account </a>
</div>
{% endif %}

{% if user.is_authenticated %}
<p class="h4" style="text-align: center;padding-top:20%">You already logged in as {{user.username}} </p>
<p class='h6' style="text-align: center"><a href="{%url 'logout'%}">logout</a> from this user first</p>
{% else %}
{% load crispy_forms_tags %}
<form action="{% url 'login' %}" method="post" style="padding-top:100px;width:400px;height:70%" class="container">
    <h1 class='display-4' style='text-align:center'> Login </h1>
    {% csrf_token %}
    {{ form|crispy }}
    <button class='btn btn-primary' type="submit">Login</button>
    <p>dont have account??<a href="{% url 'register' %}">Create new account</a></p>
</form>
{% endif %}

{% endblock %}

phonebook/templates/phonebook/logout.html
{% extends "phonebook/base.html" %}
{% block title %}Logout{% endblock %}
{% block body %}
<h3 class="display-3" style="padding-top:20%;text-align:center">You logged out</h3>
<h3 style="text-align:center">You can <a href="{%url 'login'%}">Login</a> now</h3>
{% endblock %}

phonebook/templates/phonebook/phonebook_list.html
{% load i18n %}
{% get_current_language_bidi as bidi %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body class="container">
    <dl class="row mt-5">
        <dt class="col-sm-3">{% trans "client" %}</dt>
        <dd class="col-sm-9">{{ request.user.username }}</dd>
    </dl>
    <table style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif" class="table table-bordered table-striped {% if bidi == rtl %}rtl{% endif %}">
        <h1 class="text-success rtl ">
        </h1>
        <thead>
            <tr>
                <th>#</th>
                <th>{% trans "firstname" %}</th>
                <th>{% trans "lastname" %}</th>
                <th>{% trans "phonenumber" %}</th>
            </tr>
        </thead>
        {% for contact in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ contact.first_name}}</td>
            <td>{{ contact.last_name}}</td>
            <td>{{contact.phone_number}}</td>
        </tr>
        {% endfor %}
    </table>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

phonebook/templates/phonebook/recent.html
{% extends 'phonebook/base.html' %}
{% block body %}
<h1 class="display-4">Recent activity</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">view</th>
    </tr>
  </thead>
  <tbody>
    {% for item in recent %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{item}}</td>
      <td><a href="">✏</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock body %}

phonebook/templates/phonebook/register.html
{% extends "phonebook/base.html" %}
{% load widget_tweaks %}
{%load l10n%}
{% block title %}Sign Up{% endblock %}
{% block body %}
{% load crispy_forms_tags %}
<form method="post" style="padding-top:50px; width:400px;height:70%" class='container-sm'>
    <h1 class='display-4' style='text-align:center'> Sign Up </h1>
    {% csrf_token %}
    {{ form|crispy}}
    <button type="submit" class='btn btn-primary'>Sign up</button>
    <p>Already have an Account <a href="{% url 'login' %}">Login</a> Now</p>
</form>

{% endblock %}

phonebook/templates/phonebook/search.html
{% extends 'phonebook/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
{% load i18n %}
<form class="form-inline my-2 my-lg-0" id="search_form">
    <h5> {% trans "phonenumber" %}:</h5>
    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" id="query">
    <select class="form-control" id="mode">
        <option value="1">find the exact number</option>
        <option value="2">number that start with your input </option>
        <option value="3">number that ends with your input</option>
        <option value="4">number that contain your input</option>
    </select>
</form>
<button class="btn btn-outline-success my-2 my-sm-0" id="search-btn">🔎</button>
<div id="output-div"></div>

{% endblock body %}
{% block scripts %}
<script>
    $(document).ready(function () {
        $('#search-btn').click(function () {
            var query_text = $('#query').val();
            var selected_mod = $('#mode').val();
            if (selected_mod == '3' ){
                query_text = '.*'+query_text+'$' //parse entry to regex for searching end of phone numbers
            }
            var ajax_config = {
                url: "/api/v1/contact/",
                data: {
                    search: query_text,
                    mode : selected_mod
                },
                method: 'GET',
                success: function (response) {
                    var my_output_div = $('#output-div');
                    var table = "";
                    $(response).each(function (index, obj) {
                        console.log(obj);
                        var my_table = '<tr><td>' + obj.first_name + '</td><td>' + obj.last_name + '</td><td>' + obj.phone_number + '</td></tr>';
                        table = table + my_table;
                    });
                    if (my_output_div.is(':empty')) {
                        final_table = '<table class="table table-bordered table-striped" ><thead><tr><th>{% trans "firstname" %}</th><th>{% trans "lastname" %}</th><th>{% trans "phonenumber" %}</th></tr></thead><tbody>' + table + '</tbody></table>';
                        my_output_div.append(final_table);
                        my_output_div.append(response.length + ' resault found');
                    } else {
                        my_output_div.empty();
                        final_table = '<table class="table table-bordered table-striped" ><tr><th>{% trans "firstname" %}</th><th>{% trans "lastname" %}</th><th>{% trans "phonenumber" %}</th></tr>' + table + '</table>';
                        my_output_div.append(final_table);
                        my_output_div.append(response.length + ' resault found');
                    }
                }
            }
            $.ajax(ajax_config);
        });
    });
</script>
{% endblock scripts %}

phonebook/templates/phonebook/switch_lang.html
{% load i18n %}
<form action="{% url 'set_language' %}" method="post">  
    {% csrf_token %}  
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}  
        {% get_available_languages as LANGUAGES %}  
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}> 
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Switch">
</form>